name: Deploy complex(multi-docker) app to Elastic Beanstalk
on:
  push:
    branches:
      - master

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build ./client -t mhorvat85/multi-client:latest
          docker build ./nginx -t mhorvat85/multi-nginx:latest
          docker build ./server -t mhorvat85/multi-server:latest
          docker build ./worker -t mhorvat85/multi-worker:latest
      - name: publish
        run: |
          docker push mhorvat85/multi-client:latest
          docker push mhorvat85/multi-nginx:latest
          docker push mhorvat85/multi-server:latest
          docker push mhorvat85/multi-worker:latest

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: multi-docker-env
          existing_bucket_name: elasticbeanstalk-eu-central-1-342881459697
          region: eu-central-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
